# Generated by Django 3.2.10 on 2024-02-07 07:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('current_power', models.FloatField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='LuDeviceType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LuStatusDevice',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('current_power', models.FloatField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.device')),
                ('device_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.ludevicetype')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='device_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.ludevicetype'),
        ),
        migrations.AddField(
            model_name='device',
            name='status_device_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.lustatusdevice'),
        ),
    ]
