# Generated by Django 3.2.10 on 2024-02-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="updated_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
